#ifndef CONFIG_HPP
#define CONFIG_HPP

// This file is auto-generated by mconfig-gen.cc.

// Defines

// Constants
constexpr static char SYSCONTROLSOCKET[] = "/dev/dinitctl";
constexpr static char SBINDIR[] = "/sbin";
constexpr static char SHUTDOWN_PREFIX[] = "";

#endif /* CONFIG_HPP */
